### ISSUE TITLE
Theater Insert Functionality

### ISSUE THREAD

**Issue by billytherex** [sPOiDar/fvtt-module-stream-view#22]
As of now the only way to view characters using the Theater Insert module is to have the chat bar fully enabled, is there a way to allow Theater Inserts to be seen normally on the streamer account? Essentially, I'm pretty sure they're just being hidden since Theater Insert's "stage" is part of chat.

**Comment by sPOiDar** [comment]
Theatre Inserts seems to be generally broken for me on Foundry v9 - it throws a bunch of errors when trying to use various features, even in a clean world with no other modules.

As to your issue, TBH I'm not really sure what I should be looking at - the Narrator mode does work - it pops the message up, and those messages show up in chat as they should. Since the module is broken I can't test the actor features.

**Comment by sPOiDar** [comment]
Closing due to lack of feedback, feel free to reopen if you can confirm these issues.
