### ISSUE TITLE
[Feature request] Focus on a specific player / group and token vision

### ISSUE THREAD

**Issue by Kurokasa** [sPOiDar/fvtt-module-stream-view#24]
Hi, first of all thx for the work you already put in for us :).

I pitched this in the foundry Discord but in short it would be gr8 if it was possible to follow only a specific player, token or group of players since big maps with MLT etc. often zoom out the view so far that you cant see anything anymore.
I would also love if it was possible to change the view from an observing point to the real token vision when in single use, or as an extra option. This would not only fix the issue with roofs and other overhead tiles not fading "properly", but might also fix the compatibility with levels. I know at this point it would basically just be a cam view that follows its owned token arround, but i think this might be a workarround for future compatibilitys.

I hope you give this a chance and iam more that glad to pitch a few ideas arround to find the best version of this.

**Comment by sPOiDar** [comment]
There are a bunch of different requests muddled in here:

1. Allow tracking specific tokens in auto-camera mode
2. Display the union of vision for the currently tracked tokens
3. Compatibilty with Levels

I've fixed `1` with the latest update - you can select a set of tokens and right-click then click the camera icon to toggle tracking, when in automatic mode. The GM will see a tracking icon on the currently active tokens.

To achieve `2` would require some serious hacking of the Foundry vision code, since currently we just rely on the vision granted by the Observer permission. I have no interest in doing this personally.

As explained elsewhere, `3` is not going to happen unless Levels changes how they manage this, or until Foundry core releases a fully-functional levels implementation, which will likely support this use-case without us having to do anything.
