### ISSUE TITLE
Ambient sounds

### ISSUE THREAD

**Issue by moonwolf-github** [sPOiDar/fvtt-module-stream-view#26]
It seems that ambient sounds are not supported. Is there a way to do this?

**Comment by sPOiDar** [comment]
Hmm, possibly - Foundry relies on a token being selected to play ambient audio, and only token owners (or GMs) can select tokens, not observers.

Would probably have to patch some Foundry code to make ambient sounds consider all tokens selected at all times, this would mean you'd hear sounds for all tokens no matter how far apart they are, might mean you get multiple sounds playing from different parts of the map if your party is split.

**Comment by moonwolf-github** [comment]
Or maybe place an invisible token owned by the stream user near the currently followed token? Is this possible?

**Comment by sPOiDar** [comment]
There isn't really a concept of "currently followed token" - in automatic mode, that's most frequently all tokens, in directed mode the GM can point the camera where ever they like.

We could maybe fake a token at the center of the screen, but that's frequently unlikely to yield very useful results.

**Comment by moonwolf-github** [comment]
It's better than nothing i suppose... Or maybe stick this fake token to one chosen by GM?

**Comment by moonwolf-github** [comment]
As a workaround I made an Actor owned by the stream user and using "Follow Me!" module bound his token to the token of one of the players. I'll test it tonight and we'll see.

**Comment by sPOiDar** [comment]
I tested out playing sound at the center of the camera position. Seems to work pretty well, since the viewer hears sounds as if they're at the center of the screen.

If your player tokens are very far away from each other you may not hear what they hear, and whilst it would be possible (if a little more complicated) to play everything that all tokens can hear, but I'm not sure if that would actually be an improvement, since then you might have conflicting audio playing from different parts of the map.

I think I'm happier with the screen center option, and will likely package this up for release.

**Comment by sPOiDar** [comment]
Available in v1.2.0
