### ISSUE TITLE
Stream view module no longer works with Lockview

### ISSUE THREAD

**Issue by JavaShipped** [sPOiDar/fvtt-module-stream-view#30]
Foundry version: 9v280
D&D5e Version: 1.6.3

I have used "find the culprit" to narrow down a compatibility error between lock view and stream view.

When stream view is active (user selected as the stream view), that user's screen isn't locked correctly. The 'camera'/ view is very stretched over to the right of the screen.

This is what it looks like for the 'stream view' user with stream view disabled, and lock view on:
![image](https://user-images.githubusercontent.com/29931954/190466277-ead11ab5-6f12-439d-a9e7-d314ef5f9a1c.png)

This is what it looks like for the 'stream view' user with stream view enabled (see settings below), and lock view on
![image](https://user-images.githubusercontent.com/29931954/190467016-7fbbfed1-3ad9-48d2-987e-0ec86cb22179.png)
The same image but zoomed out (pan locked)
![image](https://user-images.githubusercontent.com/29931954/190467082-cc2f9389-c3e8-41e2-8161-baa6988731ea.png)

If it helps - Earnies Modern UI seemed to have a [very similar issue](https://github.com/ernieayala/ernies-modern-layout/issues/164), but no other UI modules seem to break.

**Comment by sPOiDar** [comment]
Last time this happened it was due to a code error in Lock View (#10).

Looking now, I can see that Lock View appears to be broken on v9:

```
sceneConfig.js:316 Uncaught TypeError: Cannot read properties of undefined (reading 'scale')
[Detected 1 package: LockView]
    at InitialViewBox.updateBox (sceneConfig.js:316:46)
    at HTMLButtonElement.<anonymous> (sceneConfig.js:694:28)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

Though on both v9 and v10 I can't seem to use the Lock View control buttons, it just tells me there's no client connected on the scene. I don't use the module in general though, so not sure how long that's been the case.

Either way, I doubt there's anything to be done on this side. I'm going to close this out for now, but please feel free to reopen if you discover that Stream View can do anything to help resolve this.
