### ISSUE TITLE
Not very compatible with the Levels module

### ISSUE THREAD

**Issue by magroader** [sPOiDar/fvtt-module-stream-view#43]
The Stream View mod doesn't really work when paired with the Levels module.

Here's a huge map of Castle Ravenloft that uses Levels:
https://www.reddit.com/r/CurseofStrahd/comments/sb6raj/my_singlescene_castle_ravenloft_in_foundry_is_now/

I tried this with Stream View, and the stream player was basically just showing the roof the entire time. It handled movement just fine, but would need to somehow work with Levels to hide content based on what elevation some player is on.

Suggestion: arbitrarily pick a player somehow, maybe the last one to have moved, when on a map with Levels, and show the map from their point of view?

Or perhaps which Level the GM has chosen? When using Levels the GM decides how they view the map.

**Comment by sPOiDar** [comment]
Yeah, Levels unfortunately won't be supported in its current state, since it doesn't natively support multiple tokens or shared vision, see #21 where the module author said they *might* consider adding support at some stage. I expect once core gets around to implementing levels it will be a different story.
