### ISSUE TITLE
Chat window closes when clicking the scene/board and cannot re-open it

### ISSUE THREAD

**Issue by jrbuda** [sPOiDar/fvtt-module-stream-view#51]
![image](https://user-images.githubusercontent.com/47678481/222877251-fc5408a4-9d99-4193-b0d9-9580a6b18e1a.png)
Before clicking^

After clicking:
![image](https://user-images.githubusercontent.com/47678481/222877263-a10e6729-d67e-45ba-8f4b-7dfe5cdc992b.png)

It turns into a small box in the top left corner and cannot be re-opened without refreshing the connection. May be related to another module but I am not sure how to check for that.

**Comment by jrbuda** [comment]
After more investigation, it is a weird interaction with the Window Controls module. That module essentially minimizes sheets when you click off of them and puts them into a taskbar of sorts. I guess it is trying to minimize the chat window when I click off of it.

**Comment by sPOiDar** [comment]
The chat window is a popout under Stream View, since we hide the rest of the sidebar. In general though I wouldn't expect users to be interacting with the streamed view/user, but either way since it's another module doing the hiding, maybe see if they have a way to ignore certain windows or if it can be disabled per-user.

Going to close this out here, since it's not something I'm interested in trying to hack around on this side.
