### ISSUE TITLE
Installation links of older versions point to latest version instead

### ISSUE THREAD

**Issue by DrainBread** [sPOiDar/fvtt-module-stream-view#52]
I'm trying to get the manifest URL for the version compatible with FoundryVTT v9 but it seems to point to the latest version instead which requires v10. I checked the older versions and they are all the same manifest. Could you please provide a link for version 0.4.2 compatible with v9?

**Comment by sPOiDar** [comment]
The manifest for the last version supporting v9 (0.4.4) can be found here: https://github.com/sPOiDar/fvtt-module-stream-view/raw/8ee3519dfd23a04ca8a9d318603d3d3c0a13c8cf/module.json

Internally the manifest necessarily has to point to the latest version for upgrades to work, that's a Foundry limitation, though I don't think Foundry should try to upgrade to an incompatible version (they have made breaking changes to the manifest format though, so not sure how v9 will deal with that). Foundry does have an option to lock modules so that they don't update, but... that might be a v10 feature, IIRC. It's probably time to think about upgrading to v10.
