### ISSUE TITLE
Foundry window in the background doesn't update

### ISSUE THREAD

**Issue by odhinn33** [sPOiDar/fvtt-module-stream-view#60]
Foundry V.10, Windows 11, OBS Studio v29:
I used Stream View module for the 1st time in my session yesterday evening recording from OBS. I actually discovered that I just recorded for 3 hours the landing page of Foundry Game and nothing else. I've opened an Incognito windows from Chrome for the Stream user and left it opened in the background. It seems it doesn't refresh the view and it doesn't record what is happening if the window is not shown on the display. By the time you click on it, it refreshes on what you're seeing. I don't have a third monitor to leave it opened so I hope there's a way to record it even if in the background. Maybe wrong browser? Maybe some setting I'm missing? Maybe some graphic card setting? I'm really disappointed, it has been an epic session...

**Comment by sPOiDar** [comment]
I'm afraid I don't use Windows, so I don't have a lot of good advice for you, but I believe the browser source on OBS for Windows works fine these days, so I'd suggest you try using that instead of window capture.

Support for OBS itself is really beyond the scope of what I can provide here though, and this issue is really unrelated to this module. If you're still struggling, perhaps try the Foundry Discord, or OBS forums, I'm sure someone else knows more about this than I do.
