### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by Conradhowlf** [sPOiDar/fvtt-module-stream-view#77]
**Is your feature request related to a problem? Please describe.**
I have a module from Ripper called PartyHUD

**Describe the solution you'd like**
I want PartyHUD to show while using StreamView

**Describe alternatives you've considered**
None

**Additional context**
I think I can do it myself. Another module that Ripper made named Carousel already shows while using Stream View. So I don't know if StreamView has an exception to Carousel. I think if I new where this exception is handled, if it exists. I can add Party HUD as an exception too

**Comment by sPOiDar** [comment]
StreamView doesn't do anything special for Carousel, and from a brief look at the module's wiki, Party HUD depends on Carousel, so I would expect it to work the same.

Since this is a premium module there's not much I can do to help you troubleshoot why it's not showing up. StreamView doesn't do anything fancy for module rendering though, the only thing it does anything special for is popups, all other standard application windows should be rendered as the module author intended.

Perhaps there's some setting that needs to be enabled on the stream user? You can temporarily enable the full sidebar to access the stream user settings.

I'm going to close this out for now as I don't have any way to assist. Feel free to re-open if you have additional information that might be relevant.
